
#insert the install path
INSTALLPATH := /home/pi/ortensia_ws

install:
	cp ave.csv $(INSTALLPATH)/.
	cp dht22-db.py $(INSTALLPATH)/.
	cp forecast.csv $(INSTALLPATH)/.
	cp one_day_forecast.csv $(INSTALLPATH)/.
	cp owm_api.py $(INSTALLPATH)/.
	cp weatherlib.py $(INSTALLPATH)/.
	cp weatherplotlib.py $(INSTALLPATH)/.
	cp wlutils.py $(INSTALLPATH)/.
